#
#  Basic Web Config
#
baseURL = 'https://qtekfun.netlify.com/'
languageCode = 'en-us'
title = 'Qtekfun Site'
theme = "hugo-geekblog"

pluralizeListTitles = false

MetaDataFormat = "yaml"
DefaultContentLanguage = "es" # Default languaje content
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = false
[sitemap]
  changefreq = "weekly" # Frecuency of recreation
  priority = 0.5
  filename = "sitemap.xml" # Path of sitemap

[params]
  #favicon = "" # TODO
  subtitle = "Mis movidas"
  description = "Mis movidas"
  #facebook = ""
  twitter = "https://twitter.com/qtekfun"
  instagram = "https://www.instagram.com/qtekfun/"
  youtube = "https://www.youtube.com/mrmovilianoo"
  github = "https://github.com/qtekfun/"
  linkedin = "https://www.linkedin.com/in/cmorenomateos/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  #featured_image = "/static/me.jpg"
  recent_posts_number = 2

# Geekblog required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
  author = "authors"
  tag = "tags"

[mediaTypes]
  [mediaTypes."application/atom+xml"]
    suffixes = ["xml"]

[outputFormats]
  [outputFormats.Atom]
    name = "Atom"
    mediaType = "application/atom+xml"
    baseName = "feed"
    isPlainText = false
    rel = "alternate"
    isHTML = false
    noUgly = true
    permalinkable = false

[outputs]
  home = ["HTML", "ATOM"]
  page = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML", "ATOM"]